# Generated by Django 3.0.3 on 2020-04-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Numéro du lot')),
                ('numContainer', models.CharField(max_length=12, verbose_name='Numéro du container')),
                ('isSQ', models.BooleanField(default=False, verbose_name='SQ')),
                ('isC', models.BooleanField(default=False, verbose_name='Zone C')),
                ('isF', models.BooleanField(default=False, verbose_name='Francité')),
                ('isBloque', models.BooleanField(default=False, verbose_name='Lot bloqué')),
                ('commentaires', models.CharField(blank=True, max_length=128, null=True, verbose_name='Commentaires')),
                ('betterNumContainer', models.IntegerField(default=0, verbose_name='Numéro du container en version chiffre')),
            ],
        ),
        migrations.CreateModel(
            name='Francite',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID du lot francité')),
                ('contremarque', models.CharField(blank=True, max_length=128, null=True, verbose_name='Contremarque')),
                ('produit', models.CharField(max_length=32, verbose_name='Produit')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('numLot', models.IntegerField(default=0, verbose_name='Numéro du lot')),
            ],
        ),
        migrations.CreateModel(
            name='LotBloque',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID du lot bloque')),
                ('numLot', models.IntegerField(default=0, verbose_name='Numéro du lot')),
                ('numContainer', models.CharField(max_length=12, verbose_name='Numéro du container')),
                ('contremarque', models.CharField(blank=True, max_length=128, null=True, verbose_name='Contremarque')),
                ('categorie', models.CharField(blank=True, max_length=128, null=True, verbose_name='Catégorie')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('operation', models.CharField(blank=True, max_length=128, null=True, verbose_name='Opération')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID du score')),
                ('tonnage', models.CharField(max_length=12, verbose_name='Tonnage')),
                ('depotage', models.CharField(max_length=20, verbose_name='Dépotage')),
                ('container', models.CharField(max_length=12, verbose_name='Numéro du container')),
                ('marque', models.CharField(max_length=8, verbose_name='Marque')),
                ('produit', models.CharField(max_length=32, verbose_name='Produit')),
                ('qteAnnonce', models.IntegerField(default=0, verbose_name='Qté Annoncée')),
                ('numLot', models.IntegerField(default=0, verbose_name='Numéro du lot')),
                ('gestion', models.CharField(blank=True, max_length=128, null=True, verbose_name='Gestion')),
                ('prio', models.CharField(blank=True, max_length=128, null=True, verbose_name='prio')),
                ('info', models.CharField(blank=True, max_length=128, null=True, verbose_name='info')),
                ('resultat', models.CharField(blank=True, max_length=128, null=True, verbose_name='Résultat')),
                ('mdc', models.CharField(blank=True, max_length=128, null=True, verbose_name='MDC')),
                ('ncc', models.CharField(blank=True, max_length=128, null=True, verbose_name='NC/C')),
            ],
        ),
    ]
