# Generated by Django 3.0.2 on 2020-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLot', models.IntegerField(default=0)),
                ('numContainer', models.CharField(max_length=16)),
                ('isSQ', models.BooleanField(default=0)),
                ('isC', models.BooleanField(default=0)),
                ('isF', models.BooleanField(default=0)),
                ('commentaires', models.CharField(max_length=128)),
            ],
        ),
    ]
