# Generated by Django 3.0.2 on 2020-01-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFreshApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='id',
        ),
        migrations.AddField(
            model_name='container',
            name='isBloque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='container',
            name='numLot',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
