# Generated by Django 3.0.2 on 2020-01-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFreshApp', '0003_auto_20200128_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='commentaires',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
