# Generated by Django 3.0.2 on 2020-01-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFreshApp', '0004_auto_20200128_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='numLot',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Numéro du lot'),
        ),
    ]
