# Generated by Django 3.0.2 on 2020-01-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFreshApp', '0005_auto_20200128_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='commentaires',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='container',
            name='isBloque',
            field=models.BooleanField(default=False, verbose_name='Lot bloqué'),
        ),
        migrations.AlterField(
            model_name='container',
            name='isC',
            field=models.BooleanField(default=False, verbose_name='Zone C'),
        ),
        migrations.AlterField(
            model_name='container',
            name='isF',
            field=models.BooleanField(default=False, verbose_name='Francité'),
        ),
        migrations.AlterField(
            model_name='container',
            name='isSQ',
            field=models.BooleanField(default=False, verbose_name='SQ'),
        ),
        migrations.AlterField(
            model_name='container',
            name='numContainer',
            field=models.CharField(max_length=16, verbose_name='Numéro du container'),
        ),
    ]
