# Generated by Django 3.0.2 on 2020-01-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFreshApp', '0006_auto_20200128_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='numContainer',
            field=models.CharField(max_length=12, verbose_name='Numéro du container'),
        ),
    ]
