# Generated by Django 3.0.2 on 2020-01-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFreshApp', '0007_auto_20200128_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id_score', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID du Score')),
                ('tonnage', models.CharField(max_length=12, verbose_name='Tonnage')),
                ('depotage', models.CharField(max_length=20, verbose_name='Dépotage')),
                ('container', models.CharField(max_length=12, verbose_name='Numéro du container')),
                ('marque', models.IntegerField(default=0, verbose_name='Marque')),
                ('produit', models.CharField(max_length=32, verbose_name='Produit')),
                ('qteAnnonce', models.IntegerField(default=0, verbose_name='Qté Annoncée')),
                ('numLot', models.IntegerField(default=0, verbose_name='Numéro du lot')),
                ('gestion', models.CharField(blank=True, max_length=128, null=True, verbose_name='Gestion')),
                ('prio', models.CharField(blank=True, max_length=128, null=True, verbose_name='prio')),
                ('info', models.CharField(blank=True, max_length=128, null=True, verbose_name='info')),
                ('resultat', models.CharField(blank=True, max_length=128, null=True, verbose_name='Résultat')),
                ('mdc', models.CharField(blank=True, max_length=128, null=True, verbose_name='MDC')),
                ('ncc', models.CharField(blank=True, max_length=128, null=True, verbose_name='NC/C')),
            ],
        ),
    ]
