# Generated by Django 3.0.2 on 2020-01-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFreshApp', '0008_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='id_score',
        ),
        migrations.AlterField(
            model_name='score',
            name='numLot',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Numéro du lot'),
        ),
    ]
