# Generated by Django 3.0.2 on 2020-01-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFreshApp', '0009_auto_20200130_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='marque',
            field=models.CharField(max_length=8, verbose_name='Marque'),
        ),
    ]
