# Generated by Django 3.0.2 on 2020-01-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFreshApp', '0010_auto_20200131_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='idScore',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID du score'),
        ),
        migrations.AlterField(
            model_name='score',
            name='numLot',
            field=models.IntegerField(default=0, verbose_name='Numéro du lot'),
        ),
    ]
