# Generated by Django 3.0.2 on 2020-02-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFreshApp', '0011_auto_20200131_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='betterNumContainer',
            field=models.IntegerField(default=0, verbose_name='Numéro du container en version chiffre'),
        ),
    ]
