# Generated by Django 3.0.2 on 2020-02-27 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('SmartFreshApp', '0013_lotbloque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='numLot',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='idScore',
            new_name='id',
        ),
    ]
