# Generated by Django 3.0.2 on 2020-02-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SmartFreshApp', '0015_auto_20200228_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='francite',
            name='numLot',
            field=models.IntegerField(default=0, verbose_name='Numéro du lot'),
        ),
    ]
